// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/quiz-results/Preview.tsx": () => import("../components/mockups/quiz-results/Preview.tsx"),
  "./components/mockups/styleswipe-discover/Accessibility.tsx": () => import("../components/mockups/styleswipe-discover/Accessibility.tsx"),
  "./components/mockups/styleswipe-discover/Affordance.tsx": () => import("../components/mockups/styleswipe-discover/Affordance.tsx"),
  "./components/mockups/styleswipe-discover/Hierarchy.tsx": () => import("../components/mockups/styleswipe-discover/Hierarchy.tsx")
};
